version: '2.29.7'

services:
  nginx-memory:
    image: ${{ secrets.DOCKER_USERNAME }}/memory
    container_name: nginx-memory
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always

