name: Memory Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build-memory:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2 : Construire l'image Docker et la taguer
      - name: Build and Tag Docker image
        run: docker build -t gbb1402/memory:latest .

  push-memory:
    needs: build-memory
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "gbb1402" --password-stdin

      # Pousser l'image sur Docker Hub
      - name: Push Docker image
        run: docker push gbb1402/memory:latest

