name: Memory Pipeline

on:
  push:
    branches:
      - develop

jobs:
  test-memory:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test des jpg
        run: |
          find . -type f -name '*.jpg' | while read -r file; do
            file "$file"
          done

  build-memory:
    runs-on: self-hosted
    needs: test-memory
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: connexion DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t loanlebrave/memory .

      - name: Push Docker image to DockerHub
        run: |
          docker push loanlebrave/memory

  push-memory:
    runs-on: self-hosted
    needs: build-memory
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Connexion DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to DockerHub
        run: |
          docker push loanlebrave/memory

  deploy-memory:
    runs-on: self-hosted
    needs: push-memory
    steps:
      - name: le ssh
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: deploiement du container sur un server
        env:
          DOCKER_HOST: "ssh://localhost@172.23.28.140"
        run: |
          # pour etre sur d avoir le plus récent
          git pull origin develop

          # demarrage avec docker compose en arretant les anciens
          docker-compose -f /home/localhost/tpnote/memory/docker-compose.yml down
          docker-compose -f /home/localhost/tpnote/memory/docker-compose.yml up -d
