name: Memory Pipeline

# Déclencher le workflow lors d'un push sur la branche develop
on:
  push:
    branches:
      - develop

jobs:
  build-memory:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t gbb1402/memory .

  push-memory:
    needs: build-memory
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "gbb1402" --password-stdin

      - name: Tag Docker image
        run: docker tag gbb1402/memory:latest gbb1402/memory:latest

      - name: Push Docker image
        run: docker push gbb1402/memory:latest

